---
title: "Data_Generation"
author: "Søren Orm Hansen"
date: "9/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(pacman)

p_load(tidyverse, ggplot2, plotly)
```


```{r}
# Defining variables
ntrials <- 200 # Number of trials
start <- 10 # Start guess
end <- 70 # True value
sd <- 10 # Standard deviation
lr <- c(.2, .01, .03, 0.05) # Learning rates

# Useful calculation
len <- as.numeric(length(lr))

# Making the dataframe
EV <- matrix(0, ncol = 2, nrow = ntrials * len)  %>% data.frame()
colnames(EV)[1] <- 'LR'
colnames(EV)[2] <- 'EV'

x <- rnorm(ntrials, end, sd)

for (i in 1:len){
  EV[1 + (i - 1) * ntrials, 2] <- start
  
  EV[1 + (i - 1) * ntrials, 1] <- paste('LR', lr[i], sep = '_')
}


EV$Trials <- 1:ntrials


for (i in 1:len) {
  for (t in 2:ntrials) {
    tx <- t
    t <- t + (i - 1) * ntrials
    
    EV[t, 1] <- paste('LR', lr[i], sep = '_')
    
    EV[t, 2] <- EV[t - 1, 2] + lr[i] * (x[tx] - EV[t - 1, 2])
  }
  tx <- 2
}

#EV$LR <- as.factor(EV$LR)

g <- EV %>% 
  ggplot(aes(x = Trials, y = EV, color = LR)) +
  geom_line() +
  xlab('Trial') +
  facet_wrap(~ LR) +
  geom_hline(aes(yintercept = end), linetype = 'dotted', alpha = 0.5) +
  theme_classic()

ggplotly(g)

#plot(EV, type = 'l', xlab = 'trials')

```


